### ISSUE TITLE
Login glitch 

### ISSUE THREAD

**Issue by verticalhost** [R1ck404/livestreaming_platform#1]
I'm always redirected to the home page when I ask you to display a dashboard or something.
the go live button takes me directly to the login page.

**Comment by R1ck404** [comment]
I haven't worked on this project in a while, when i created it it worked fine. But ill look into it, ill close this issue once its fixed.

**Comment by verticalhost** [comment]
Add me on discord if you want to check on my end. 
Maybe i forget to add something both .env are correct and show same information from backend to frontend. 

Here is my discord
lordwaffl3_exlusive

**Comment by R1ck404** [comment]
I pushed a fix through, this issue should be fixed now.

I would really appreciate it if you could test it on your machine.
